{% set name = "pygram11" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 477e2b3eb77f51a3b985ee21d69a5772c2d2b5d05c1a018df7ecd4b91955a53a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - numpy

test:
  requires:
    - pytest
    - numpy
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - pytest --ignore=extern

about:
  home: http://github.com/douglasdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Simple and fast histogramming in Python via pybind11 and OpenMP"
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/douglasdavis/{{ name }}

extra:
  recipe-maintainers:
    - douglasdavis
