{% set name = "pygram11" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09d24ad001e03774f60d0084649a8306b112fb1891cc2d828570fa00777273d8

build:
  number: 1
  skip: true  # [py<311 or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - python
    - llvm-openmp  # [osx]
    - numpy

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/douglasdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and fast histogramming in Python via pybind11 and OpenMP
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/douglasdavis/{{ name }}

extra:
  recipe-maintainers:
    - douglasdavis
