{% set name = "pygram11" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a89224a35f0c68099f2c0f6bd8dc0d1b505a689dcefa0138ef20d94a1c2b573

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - python
    - pip
    - setuptools >=39.0.1
    - numpy >=1.12
  run:
    - llvm-openmp  # [osx]
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - numpy >=1.12
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - pytest --ignore=extern

about:
  home: http://github.com/douglasdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Simple and fast histogramming in Python via pybind11 and OpenMP"
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/douglasdavis/{{ name }}

extra:
  recipe-maintainers:
    - douglasdavis
