{% set name = "pygram11" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6783c9c2c55a7ef9b6e41b50c42cf20559ec7f8423b6659217f186deceb17a9f

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - python
    - pip
    - setuptools >=39.0.1
    - pybind11 >=2.2
    - numpy >=1.12
  run:
    - llvm-openmp  # [osx]
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - numpy >=1.12
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - py.test

about:
  home: http://github.com/drdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Simple and fast histogramming in python via pybind11 and OpenMP"
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/drdavis/{{ name }}

extra:
  recipe-maintainers:
    - drdavis
