{% set name = "pygram11" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64e082ff958e2986f4fcd149b4d3b18544be7900b2c55cf173f07dc0743c380d

build:
  number: 1
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - python
    - llvm-openmp  # [osx]
    - numpy

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - pytest --ignore=extern

about:
  home: http://github.com/douglasdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and fast histogramming in Python via pybind11 and OpenMP
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/douglasdavis/{{ name }}

extra:
  recipe-maintainers:
    - douglasdavis
