{% set name = "pygram11" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d14a5b792ff17b6f6dea66d045d3033c670d77f81754a17f22f5b0899da77464

build:
  number: 0
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.14
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - numpy >=1.14
  source_files:
    - tests
  imports:
    - {{ name }}
  commands:
    - pytest --ignore=extern

about:
  home: http://github.com/douglasdavis/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and fast histogramming in Python via pybind11 and OpenMP
  description: |
    Simple and fast histogramming with a NumPy like API, built on pybind11 and
    accelerated with OpenMP.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/douglasdavis/{{ name }}

extra:
  recipe-maintainers:
    - douglasdavis
