travis:
  secure:
    BINSTAR_TOKEN: WN8Mj6IZOpKm7mVIGhW4AClaBiXWGVov3YK36A1GyMQm5jAh70J6rYMNOm7nlOFcu6jB0doyTfyYQkINFeZ3dlWq3VB/ftCCm6iZzyns4fuWDqzyMAwGg65IaIIf5gsTwJ0mIRorv1wuEuTRJxF11gZrBfaXw2EPh8TUmrOKrK+CmQBIrIuV++DEvLTt5kNha2xK0LjLqgZNacNIBjUtEVeNbOVt0e0MVhkKsf64aJxZiSJ6CwaNBaiVb0xeGZMOi2oeA+xteSvbrKFWfssgztoqTPE8jrnh5CJIBYSVPNWKDPYqsmtYVLLhHXXbPHUjhL3L/I7T4zdNwo0OEg9IcEanYCs4qLiduCnKeJAyyQQZDXEDCfPTxva5+1DdwGvKMW/bG1ed+u/svtNADCo1aO1eeFSQpXyaCS1fgIGNo/Y0LTKUecJmWfGuKMAy3n7K4pB6R3vzRMlD+4kMYmjCRrBAW01rkQuz7amI+ZV+pGtWbZXxsaYHCdh97QXdv5nBXQAppVSPa8foUvq+ScnuuTEGY1icE8len0Nfb1MOPhs5s2o62UE4qKPuSkcfaSZopLwrljDGU8WT57xGMuUzzRkm58IbJvA+HVsVOeWSCeC3727/Vcui3tc0YFuNJ2gDa8pyJGHclTfHEn5lg9mrMSJVk+EP76erlu/mv/8q5bc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
